### ISSUE TITLE
MSVC DLLexport/import

### ISSUE THREAD

**Issue by VFR-maniac** [l-smash/l-smash#41]
The current MSVC project file does not output the import library (.lib).
How should we implement this?
Patches and/or opinions welcome.

A simple way is definitions as follows.

#ifdef __cplusplus
#define LSMASH_EXTERN_C extern "C"
#else
#define LSMASH_EXTERN_C
#endif

#ifdef LSMASH_EXPORTS
#define LSMASH_API LSMASH_EXTERN_C __declspec( dllexport )
#else
#define LSMASH_API LSMASH_EXTERN_C __declspec( dllimport )
#endif

**Comment by dwbuiten** [comment]
Should be fixed now in master \o/

**Comment by VFR-maniac** [comment]
Thank you for your hacks!
