### ISSUE TITLE
Incorrect muxing of HEVC

### ISSUE THREAD

**Issue by msg7086** [l-smash/l-smash#45]
Source from broadcasting. Incorrect muxing.

https://www.dropbox.com/s/gdr9m6rsv3tffrt/t.hevc?dl=0

I get:

    L-SMASH isom/mov multiplexer rev1348  97d045b
    Built on Mar 29 2015 23:54:24
    [HEVC: Info]: IDR: 0, CRA: 18, BLA: 0, I: 0, P: 162, B: 360, Unknown: 0

Should be:
60 frames at all.

File structure:

    (VPS + SPS + (PPS + Frame + AUD) * 30) * 2

**Comment by VFR-maniac** [comment]
I think the issue is fixed at 624a36f .
Please confirm it.

**Comment by msg7086** [comment]
So far so good. :+1:

**Comment by VFR-maniac** [comment]
Thanks.
