### ISSUE TITLE
unsupported file

### ISSUE THREAD

**Issue by stax76** [l-smash/l-smash#54]
Hello,

this sample causes a error, it crashes several client applications trying to open the avs script.

https://www.sendspace.com/file/49zvqy

**Comment by jeeb** [comment]
Last time I checked, L-SMASH doesn't handle MPEG-TS streams. I have a feeling you wanted to open an issue with L-SMASH Works (https://github.com/VFR-maniac/L-SMASH-Works) , which is the source filter project that was originally used as an example of L-SMASH demuxing usage.
