### ISSUE TITLE
boxdumper results in segfault

### ISSUE THREAD

**Issue by canbal** [l-smash/l-smash#57]
The attached file (renamed to segfault.txt so github doesn't complain about the extension, please rename it back to segfault.mp4) is corrupted on purpose. Running boxdumper with it results in segfault. I haven't had the chance to look into a fix myself, just putting it out here. 

[segfault.txt](https://github.com/l-smash/l-smash/files/32178/segfault.txt)

**Comment by VFR-maniac** [comment]
Hi. The segfault is fixed at ee28f8d8e7a8a694eb97ab4c65e408717acc6ec6 .
But still the dump fails it seems. I'll investigate this.

**Comment by VFR-maniac** [comment]
OK. The attached file is broken, and not boxdumper's fault. The stbl box for audio track lacks 100 bytes for stsz and stco boxes.
