### ISSUE TITLE
crash with sample file from South Korea

### ISSUE THREAD

**Issue by stax76** [l-smash/l-smash#62]
Hello VFR-maniac,

I received a file from South Korea which crashes vslsmashsource.

https://mega.nz/#!KAMgATKL!xorUuCewt6FatnajMSgwsIqaquh9j3CQaGuBAVm2C8A

ID                        : 1
Format                    : AVC
Format/Info               : Advanced Video Codec
Format profile            : High@L4.1
Format settings, CABAC    : Yes
Format settings, ReFrames : 4 frames
Codec ID                  : V_MPEG4/ISO/AVC
Duration                  : 1mn 0s
Bit rate mode             : Constant
Bit rate                  : 20.4 Mbps
Nominal bit rate          : 23.0 Mbps
Width                     : 1 920 pixels
Height                    : 1 080 pixels
Display aspect ratio      : 16:9
Frame rate mode           : Variable
Frame rate                : 59.940 (59940/1000) fps
Original frame rate       : 29.970 (30000/1001) fps
Standard                  : NTSC
Color space               : YUV
Chroma subsampling        : 4:2:0
Bit depth                 : 8 bits
Scan type                 : Interlaced
Scan type, store method   : Separated fields
Scan order                : Top Field First
Bits/(Pixel*Frame)        : 0.164
Stream size               : 148 MiB (100%)
Default                   : No
Forced                    : No
Color range               : Limited
Color primaries           : BT.709
Transfer characteristics  : BT.709
Matrix coefficients       : BT.709

**Comment by HolyWu** [comment]
You are reporting issues at the wrong repository. The L-SMASH library itself isn't a source filter. The correct repository to report is https://github.com/VFR-maniac/L-SMASH-Works.

**Comment by jeeb** [comment]
Indeed, closing this issue as invalid unless a link to the actual L-SMASH library is presented.
