### ISSUE TITLE
boxdumper segfault

### ISSUE THREAD

**Issue by justinruggles** [l-smash/l-smash#63]
I can't share the sample publicly, but I have the boxdumper output up to the crash point and a gdb backtrace.

[backtrace.txt](https://github.com/l-smash/l-smash/files/167750/backtrace.txt)
[boxdumper.txt](https://github.com/l-smash/l-smash/files/167751/boxdumper.txt)

**Comment by justinruggles** [comment]
Valgrind also reports an invalid read.
[valgrind.txt](https://github.com/l-smash/l-smash/files/167756/valgrind.txt)

**Comment by VFR-maniac** [comment]
I guess the sample uses common encryption or something like that since isom_read_esds calls isom_read_unknown_box. If so, it is a known issue for me. The currrent implementation crashes with reading of encrypted files though I haven't investigate why.

**Comment by VFR-maniac** [comment]
Try https://github.com/l-smash/l-smash/commit/ee28f8d8e7a8a694eb97ab4c65e408717acc6ec6 .
This change does not print contents of esds box of encrypted files, but should work it as an unknown box.

**Comment by dwbuiten** [comment]
This should be closed, I think?

**Comment by VFR-maniac** [comment]
yeah, I think so.
