### ISSUE TITLE
Can I use L-SMASH for video/audio playback?

### ISSUE THREAD

**Issue by jimon** [l-smash/l-smash#72]
Just it's not obvious (or simply can't find a way) how to get pixel/pcm buffers from it? Or it it even possible? I guess if there are remux features, than it should be possible :)

**Comment by jeeb** [comment]
L-SMASH is strictly a demuxing/muxing library, as in works on the level of muxed samples (be they compressed or uncompressed - in latter case you would get the raw samples, yes). It doesn't contain or by itself use any sort of decoders as it strives to be a "lean and mean" toolbox/library handling ISOBMFF and similar formats. An example project utilizing L-SMASH to demux and then libavcodec for decoding of the demuxed result is [L-SMASH Works](https://github.com/VFR-maniac/L-SMASH-Works), which contains Avisynth/AVIUtl/Vapoursynth input plugin implementations.

Additionally, please do not use **issues** for such questions. If you have a question, feel free to poke the #l-smash channel on Freenode, for example.

**Comment by jimon** [comment]
Ok, thanks!

PS. Sure, but how do you expect me to know about freenode channel if this repo doesn't have any reference to it? maybe consider adding readme.md :)
