### ISSUE TITLE
iTunes metadata is not recognized at all

### ISSUE THREAD

**Issue by nu774** [l-smash/l-smash#76]
I guess this issue is due to this commit: https://github.com/l-smash/l-smash/commit/294d62ca7c96209ad251e67fc4363107e26e77cf

At preasent, when meta box is created in isom_read_meta(), default (non null) ilst field is set (copied from isom_meta_box_default).
On the other hand, when ilst field is already set, isom_read_ilst() calls isom_read_unknown_box(). 
This probably is meant to refuse the <strong>second</strong> ilst in the meta box, but it means that isom_read_ilst() <strong>always</strong> branches into isom_read_unknown_box() at present.

**Comment by VFR-maniac** [comment]
Thank you for reporting. I'll check the behavior.

**Comment by VFR-maniac** [comment]
Please check this. https://github.com/l-smash/l-smash/commit/6480a78e833bcf588adc6a982b5073f721a6bd04

**Comment by nu774** [comment]
Thanks, it works now.
