### ISSUE TITLE
muxer issue: Crash caused by null pointer access

### ISSUE THREAD

**Issue by maki-rxrz** [l-smash/l-smash#77]
The first bug report is the following posts. (japanese)
http://mevius.2ch.net/test/read.cgi/avi/1462270195/740-742,746

If the input file path was invalid, muxer crashes.
>  muxer.exe -i \<invalid-file-path\> -o \<output\>
>
>  [Error]: failed to open \<invalid-file-path\>.
>  --> Application crash!

I confirmed that this crash is caused by null pointer access.
Please confirm the following patch.
https://gist.github.com/maki-rxrz/ee6ebea99f01f4e8b81a0d487abe56a1

**Comment by VFR-maniac** [comment]
https://github.com/l-smash/l-smash/commit/d6f03e49661f4bb761eb749cafc257ccf1dd3c7e
Applied. Thanks.
