### ISSUE TITLE
muxer freeze(or crash) when using x265 2.7+17

### ISSUE THREAD

**Issue by enctac** [l-smash/l-smash#82]
x265側の問題という可能性もありますが、仮にそうであっても
フリーズやクラッシュへの対策は必要かと思いましたので報告。
x265側については、とりあえずDoom9で質問中です。
　https://forum.doom9.org/showthread.php?p=1837506#post1837506

**問題点**
x265 2.7+17のストリームをmuxer.exeでmuxするとフリーズまたはクラッシュすることがある。
問題が発生するかどうかは、ソースや設定オプション等による。
同じソースや設定でも、x265 2.7+14のストリームでは問題は発生しない。

**各バイナリのバージョン**
L-SMASH r1450/r1459/r1466
x265 2.7+14-d7c26df32fae:[Windows][MSVC 1913][64 bit] 8bit+10bit+12bit
x265 2.7+17-2e370d98c806:[Windows][MSVC 1913][64 bit] 8bit+10bit+12bit
※L-SMASH r1466のみ自ビルド。他はrigaya氏のビルド。

**再現手順**
```
sample.avs
ColorBarsHD(1280,720).Trim(0,500).ConvertToYV12()
ShowFrameNumber(scroll=true,size=128)

ffmpeg.exe -i sample.avs -f yuv4mpegpipe - | x265.exe --y4m - --pass 1 --bitrate 1000 -o sample.265
ffmpeg.exe -i sample.avs -f yuv4mpegpipe - | x265.exe --y4m - --pass 2 --bitrate 1000 -o sample.265

muxer.exe -i "sample.265"?fps=30000/1001 -o sample.mp4
```
※追記：オプションに --preset slow あるいは --preset fast をつけると問題は再現しない
※追記：sample.avsの末尾に Spline36Resize(640,360) をつけると問題は再現しない

**その他**
x265 2.7+17のストリームをffmpegやMP4BoxでMP4にmuxした場合は特に問題ないようです。
LAV Filters 0.71を使った再生もうまくいくようです。
```
ffmpeg-3.4.2.exe -r 30000/1001 -i sample.265 -c:v copy sample.mp4 
MP4Box-0.7.2-rev442-g508d7817.exe -add sample.265 -new sample.mp4 
```

**関連**
https://rigaya34589.blog.fc2.com/blog-entry-943.html#comment4937
http://mevius.5ch.net/test/read.cgi/avi/1511263100/104-

**Comment by VFR-maniac** [comment]
サンプルファイルの提供お願いできますか？
ここに貼りづらいものの場合, メールで送ってくださっても構いません。

**Comment by rigaya** [comment]
こちらで再現したものを置きました。
raw HEVC: https://1drv.ms/u/s!AsYziax1Q91rswqzBLSdYcPV5shk
ログ: https://1drv.ms/t/s!AsYziax1Q91rswmGvsVdEuB6GW_e

ただ、x265のバージョンに依存することから、どちらかというとx265の問題のように思います。

**Comment by enctac** [comment]
失礼しました。上の再現手順で書いたsample.265相当のファイルを以下に置きました。
2.7+14で作ったもの(問題無し)と、2.7+17で作ったもの(問題あり)を入れてあります。
　http://www.mediafire.com/file/z76opz6geehha3h/sample265.zip

根本的な原因はx265側のバグだったようで、現在修正中のようです。
https://mailman.videolan.org/pipermail/x265-devel/2018-March/011677.htmlhttps://forum.doom9.org/showthread.php?p=1837703#post1837703

L-SMASH側の処理としてはエラーを出して終われれば良いのかなとは思いますが、
そのあたりはよくわかっておりませんので、おまかせいたします。

**Comment by VFR-maniac** [comment]
予想はしてましたが out-of-bound が原因なのわかりました。
んー、 SEI RBSP の長さ計ってないから `nalu_import_rbsp_from_ebsp` で長さも返せるようにするか, byte counter を使うかしないとあかんなー。 前者の方がいいかなぁ。今回は。 byte counter 実装に問題あるしなぁ。

**Comment by VFR-maniac** [comment]
対策入れました。
https://github.com/l-smash/l-smash/commit/6027dc13809791996d917827865f84f20e05cf37

**Comment by enctac** [comment]
対応ありがとうございます。後で試してみようと思います。

なお問題を起こしていたx265の方もパッチが出たようなので、
近日中に反映されるものと思われます。
https://mailman.videolan.org/pipermail/x265-devel/2018-March/011678.html

**Comment by enctac** [comment]
x265 2.7+20のコミットで修正されたようです。
https://bitbucket.org/multicoreware/x265/commits/3440a56acc7865dcdea725b8ce7755450209a8ee
