### ISSUE TITLE
codecs/h264.c cannot be used independently by importing functions

### ISSUE THREAD

**Issue by ghost** [l-smash/l-smash#94]
Hi guys,
It seems that calling `h264_setup_parser` ,followed by `h264_cleanup_parser` causes Bus Error on Ubuntu platform for my simple [C test program](https://gist.github.com/kishore-saldanha/84a05d27b3c779e30a8035336a8153d6#file-check_lsmash_h264-c) . I have added some fprintf's in the h264 source code and also provided sample output.
Also it seems that memory allocated to `h264.info.buffer` field is getting allocated in the function but is freed immediately after return . As you can see from the [output](https://gist.github.com/kishore-saldanha/84a05d27b3c779e30a8035336a8153d6#file-output-of-check_lsmash-c) that the addresses in the function `h264_setup_parser` and the application have an offset of 24 bytes (this is constant). 
I have tried it with lsmash dynamic and static library same results

**Comment by dwbuiten** [comment]
These symbols are not part of the public API or ABI, and there are no guarantees on how they work or what assumptions (like, in this case, which functions should get called in between) are present.

**Comment by ghost** [comment]
I see. Please put a note in the h264.h file . I saw a CPP video library importing them causing it to crash on some OS's like Ubuntu.

**Comment by dwbuiten** [comment]
`h264.h` is not installed by `make install`, so a note would be pretty silly.
